services:

  mysql:
    image: mysql:8.4
    container_name: mes-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "${MYSQL_PORT}:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./BD/setup_scripts/MySQL:/docker-entrypoint-initdb.d:ro

    networks:
      - mes

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} --silent"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s


  clickhouse:
    image: clickhouse/clickhouse-server:25.8
    container_name: mes-clickhouse
    restart: unless-stopped

    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DATABASE}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT}
    ports:
      - "${CLICKHOUSE_HTTP_PORT}:8123"
      - "${CLICKHOUSE_NATIVE_PORT}:9000"

    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server

    networks:
      - mes

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  clickhouse-init:
    image: clickhouse/clickhouse-server:25.8
    container_name: mes-clickhouse-init

    depends_on:
      clickhouse:
        condition: service_healthy

    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE}

    volumes:
      - ./BD/setup_scripts/ClickHouse:/scripts:ro

    networks:
      - mes

    entrypoint: ["/bin/bash", "-c"]

    command:
      - |
        set -e
  
        echo "Waiting for ClickHouse..."
  
        until clickhouse-client \
          --host clickhouse \
          --user "$$CLICKHOUSE_USER" \
          --password "$$CLICKHOUSE_PASSWORD" \
          --database "$$CLICKHOUSE_DATABASE" \
          --query "SELECT 1" >/dev/null 2>&1
        do
          sleep 1
        done
  
        echo "ClickHouse is ready."
  
        for file in /scripts/*.sql; do
          echo "Executing $$file..."
  
          clickhouse-client \
            --host clickhouse \
            --user "$$CLICKHOUSE_USER" \
            --password "$$CLICKHOUSE_PASSWORD" \
            --database "$$CLICKHOUSE_DATABASE" \
            --multiquery < "$$file"
        done
  
        echo "ClickHouse initialization completed."

    restart: "no"



networks:
  mes:
    name: mes-network

volumes:
  mysql_data:
    name: mes-mysql-data

  clickhouse_data:
    name: mes-clickhouse-data

  clickhouse_logs:
    name: mes-clickhouse-logs